on: [push]
name: Luhny.rs CI
jobs:
  build_and_test:
    name: Luhny.rs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - name: "Run a validation. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -i 353879234252633
      - name: "Run a validation. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --inn 353879234252633